<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.github.open-commons</groupId>
    <artifactId>open-commons-spring-web-dependencies</artifactId>
    <version>0.8.0-SNAPSHOT</version>
    <relativePath /> <!-- lookup parent from repository -->
  </parent>
  <artifactId>open-commons-spring-web</artifactId>
  <version>0.8.0</version>
  <name>Open Commons for Spring Web</name>
  <description>Open Commons Spring Web Project</description>
  <url>https://github.com/open-commons/open-commons-spring-web</url>

  <licenses>
    <license>
      <name>Apache License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
      <distribution>repo</distribution>
    </license>
  </licenses>

  <scm>
    <connection>
      scm:git:https://github.com/open-commons/open-commons-spring-web.git</connection>
    <developerConnection>
      scm:git:https://github.com/open-commons/open-commons-spring-web.git</developerConnection>
    <url>https://github.com/open-commons/open-commons-spring-web</url>
  </scm>

  <developers>
    <developer>
      <name>Park, Jun-Hong</name>
      <email>parkjunhong77@gmail.com</email>
      <organization>https://github.com/open-commons</organization>
      <organizationUrl>https://github.com/open-commons</organizationUrl>
    </developer>
  </developers>

  <properties>
    <!-- >>> begin: plugin dependencies -->
    <build.finalName>open-commons-spring-web-${project.version}</build.finalName>

    <encoding>UTF-8</encoding>
    <java.version>1.8</java.version>

    <compile.encoding>UTF-8</compile.encoding>
    <compile.source.version>1.8</compile.source.version>
    <compile.target.version>1.8</compile.target.version>
  </properties>

  <distributionManagement>
    <repository>
      <id>maven-central</id>
      <url>https://central.sonatype.com</url>
    </repository>
    <snapshotRepository>
      <id>ymtech-maven-repo</id>
      <name>Snapshot Repository</name>
      <url>https://nexus3.ymtech.co.kr/repository/maven-snapshots/</url>
    </snapshotRepository>
  </distributionManagement>

  <repositories>
    <!-- ===== -->
    <repository>
      <id>central</id>
      <name>Central Repository</name>
      <url>https://repo1.maven.org/maven2/</url>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
    <repository>
      <id>ymtech-maven-repo</id>
      <name>YMTECH Maven Repository</name>
      <url>https://nexus3.ymtech.co.kr/repository/maven-public/</url>
      <layout>default</layout>
    </repository>
  </repositories>

  <pluginRepositories>
    <!-- >>> Maven Central -->
    <pluginRepository>
      <id>central</id>
      <name>Central Repository</name>
      <url>https://repo1.maven.org/maven2</url>
    </pluginRepository>
  </pluginRepositories>


  <dependencies>
    <!-- ********************** -->
    <!-- begin: spring-framework -->
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-core</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-webmvc</artifactId>
    </dependency>
    <!-- end: spring-framework -->
    <!-- ********************** -->

    <!-- ********************** -->
    <!-- begin: spring boot -->
    <!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-configuration-processor</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
    <!-- end: spring boot -->
    <!-- ********************** -->

    <!-- ********************** -->
    <!-- begin: Spring Security -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-security</artifactId>
    </dependency>
    <!-- end: Spring Security -->
    <!-- ********************** -->

    <!-- ************** -->
    <!-- begin: Pagination -->
    <!--
    https://mvnrepository.com/artifact/org.springframework.data/spring-data-commons -->
    <dependency>
      <groupId>org.springframework.data</groupId>
      <artifactId>spring-data-commons</artifactId>
    </dependency>
    <!-- end: Pagination -->
    <!-- ************** -->

    <!-- ************** -->
    <!-- >>> begin: Validation -->
    <!--
    https://mvnrepository.com/artifact/jakarta.validation/jakarta.validation-api -->
    <dependency>
      <groupId>jakarta.validation</groupId>
      <artifactId>jakarta.validation-api</artifactId>
    </dependency>
    <!-- https://mvnrepository.com/artifact/com.google.code.findbugs/jsr305 -->
    <dependency>
      <groupId>com.google.code.findbugs</groupId>
      <artifactId>jsr305</artifactId>
    </dependency>
    <!-- <<< end: Validation -->
    <!-- ************** -->

    <!-- ********************** -->
    <!-- begin: slf4j -->
    <!-- https://mvnrepository.com/artifact/org.slf4j/slf4j-api -->
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>
    <!-- end: slf4j -->
    <!-- ********************** -->

    <!-- ********************** -->
    <!-- begin: refletions -->
    <!-- https://mvnrepository.com/artifact/org.reflections/reflections -->
    <dependency>
      <groupId>org.reflections</groupId>
      <artifactId>reflections</artifactId>
    </dependency>
    <!-- end: reflections -->
    <!-- ********************** -->

    <!-- ************** -->
    <!-- begin: httpclient -->
    <!-- https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient -->
    <dependency>
      <groupId>org.apache.httpcomponents</groupId>
      <artifactId>httpclient</artifactId>
    </dependency>
    <!-- end: httpclient -->
    <!-- ************** -->

    <!-- ************** -->
    <!-- begin: servlet -->
    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>javax.servlet-api</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- end: servlet -->
    <!-- ************** -->

    <!-- ************** -->
    <!-- begin: jackson -->
    <!--
    https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-annotations -->
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-annotations</artifactId>
    </dependency>
    <!-- end: jackson -->
    <!-- ************** -->

    <!-- ************** -->
    <!-- begin: open.commons -->
    <dependency>
      <groupId>io.github.open-commons</groupId>
      <artifactId>open-commons-core</artifactId>
    </dependency>
    <dependency>
      <groupId>io.github.open-commons</groupId>
      <artifactId>open-commons-ssh</artifactId>
    </dependency>
    <!-- end: open.commons -->
    <!-- ************** -->

    <!-- ************** -->
    <!-- begin: REST API Documentation -->

    <!-- https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-ui -->
    <dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-ui</artifactId>
    </dependency>

    <!-- end: REST API Documentation -->
    <!-- ************** -->

    <!-- ************** -->
    <!-- begin: Aspect -->
    <dependency>
      <groupId>org.aspectj</groupId>
      <artifactId>aspectjweaver</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-aop</artifactId>
    </dependency>

    <!-- end: Aspect -->
    <!-- ************** -->

  </dependencies>

  <build>
    <finalName>${build.finalName}</finalName>
    <defaultGoal>install</defaultGoal>
    <sourceDirectory>src/main/java</sourceDirectory>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
        <includes>
          <include>**/*.*</include>
        </includes>
      </resource>
      <resource>
        <directory>${project.basedir}</directory>
        <includes>
          <include>LICENSE</include>
        </includes>
        <targetPath>META-INF</targetPath>
      </resource>
    </resources>
    <plugins>
      <!-- >>> begin: compile -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <encoding>${compile.encoding}</encoding>
          <source>${compile.source.version}</source>
          <target>${compile.target.version}</target>
        </configuration>
      </plugin>
      <!-- <<< end: compile -->
      <!-- >>> begin: source -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-source-plugin</artifactId>
        <configuration>
          <encoding>UTF-8</encoding>
        </configuration>
        <executions>
          <execution>
            <id>attach-sources</id>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <!-- <<< end: source -->
      <!-- >>> begin: javadoc -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <configuration>
          <goal>deploy</goal>
          <show>private</show>
          <nohelp>true</nohelp>
          <additionalOptions>
            <additionalOption>-Xdoclint:none</additionalOption>
          </additionalOptions>
          <charset>${encoding}</charset>
          <docencoding>${encoding}</docencoding>
          <encoding>${encoding}</encoding>
        </configuration>
        <executions>
          <execution>
            <id>attach-javadocs</id>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <!-- <<< end: javadoc -->
      <!-- Maven Central Deployment plugin -->
      <plugin>
        <groupId>org.sonatype.central</groupId>
        <artifactId>central-publishing-maven-plugin</artifactId>
        <version>0.7.0</version>
        <extensions>true</extensions>
        <configuration>
          <publishingServerId>maven-central</publishingServerId>
          <!-- autoPublish>true</autoPublish>
             		<waitUntil>published</waitUntil -->
        </configuration>
      </plugin>
      <!-- GPG signature plugin -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-gpg-plugin</artifactId>
        <version>1.5</version>
        <executions>
          <execution>
            <id>sign-artifacts</id>
            <phase>verify</phase>
            <goals>
              <goal>sign</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>