<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.github.open-commons</groupId>
    <artifactId>open-commons-spring-web-dependencies</artifactId>
    <version>4.0.0-SNAPSHOT</version>
    <relativePath /> <!-- lookup parent from repository -->
  </parent>
  <artifactId>open-commons-spring-web</artifactId>
  <name>Open Commons for Spring Web</name>
  <description>Open Commons Spring Web Project</description>
  <url>https://github.com/open-commons/open-commons-spring-web</url>

  <licenses>
    <license>
      <name>Apache License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
      <distribution>repo</distribution>
    </license>
  </licenses>

  <scm>
    <connection>
      scm:git:https://github.com/open-commons/open-commons-spring-web.git</connection>
    <developerConnection>
      scm:git:https://github.com/open-commons/open-commons-spring-web.git</developerConnection>
    <url>https://github.com/open-commons/open-commons-spring-web</url>
  </scm>

  <developers>
    <developer>
      <name>Park, Jun-Hong</name>
      <email>parkjunhong77@gmail.com</email>
      <organization>https://github.com/open-commons</organization>
      <organizationUrl>https://github.com/open-commons</organizationUrl>
    </developer>
  </developers>

  <properties>
    <build.finalName>open-commons-spring-web-${project.version}</build.finalName>
  </properties>

  <distributionManagement>
    <repository>
      <id>maven-central</id>
      <url>https://central.sonatype.com</url>
    </repository>
    <snapshotRepository>
      <id>ymtech-maven-repo</id>
      <name>Snapshot Repository</name>
      <url>https://nexus3.ymtech.co.kr/repository/maven-snapshots/</url>
    </snapshotRepository>
  </distributionManagement>

  <repositories>
    <!-- ===== -->
    <repository>
      <id>central</id>
      <name>Central Repository</name>
      <url>https://repo1.maven.org/maven2/</url>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
    <repository>
      <id>ymtech-maven-repo</id>
      <name>YMTECH Maven Repository</name>
      <url>https://nexus3.ymtech.co.kr/repository/maven-public/</url>
      <layout>default</layout>
    </repository>
  </repositories>

  <pluginRepositories>
    <!-- >>> Maven Central -->
    <pluginRepository>
      <id>central</id>
      <name>Central Repository</name>
      <url>https://repo1.maven.org/maven2</url>
    </pluginRepository>
  </pluginRepositories>


  <dependencies>
    <!-- ********************** -->
    <!-- begin: spring boot -->
    <!-- Web MVC -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
      <exclusions>
        <exclusion>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-logging</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot -->
    <!-- `@ConfigurationProperties` 메타데이터 생성용 -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-configuration-processor</artifactId>
    </dependency>

    <!-- Aspect -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-aop</artifactId>
    </dependency>
    <!-- end: spring boot -->
    <!-- ********************** -->

    <!-- ********************** -->
    <!-- begin: Spring Security -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-security</artifactId>
      <optional>true</optional>
      <exclusions>
        <exclusion>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-logging</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>org.springframework.security</groupId>
      <artifactId>spring-security-access</artifactId>
    </dependency>
    <!-- end: Spring Security -->
    <!-- ********************** -->

    <!-- ********************** -->
    <!-- >>> begin: logging -->
    <!-- https://mvnrepository.com/artifact/com.lmax/disruptor -->
    <!-- for llog4j-2.x: making all asynchronous loggers -->
    <dependency>
      <groupId>com.lmax</groupId>
      <artifactId>disruptor</artifactId>
    </dependency>

    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-core</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-slf4j2-impl</artifactId>
    </dependency>
    <!-- <<< end: logging -->
    <!-- ********************** -->


    <!-- ************** -->
    <!-- begin: servlet -->
    <dependency>
      <groupId>jakarta.servlet</groupId>
      <artifactId>jakarta.servlet-api</artifactId>
    </dependency>
    <!-- end: servlet -->
    <!-- ************** -->

    <!-- ************** -->
    <!-- begin: Pagination -->
    <!--
    https://mvnrepository.com/artifact/org.springframework.data/spring-data-commons -->
    <dependency>
      <groupId>org.springframework.data</groupId>
      <artifactId>spring-data-commons</artifactId>
    </dependency>
    <!-- end: Pagination -->
    <!-- ************** -->

    <!-- ************** -->
    <!-- >>> begin: Validation -->
    <!--
      https://mvnrepository.com/artifact/jakarta.validation/jakarta.validation-api -->
    <dependency>
      <groupId>jakarta.validation</groupId>
      <artifactId>jakarta.validation-api</artifactId>
    </dependency>
    <!-- <<< end: Validation -->
    <!-- ************** -->

    <!-- ************** -->
    <!-- >>> begin: Annotation -->
    <!-- Source: https://mvnrepository.com/artifact/org.jspecify/jspecify -->
    <dependency>
      <groupId>org.jspecify</groupId>
      <artifactId>jspecify</artifactId>
    </dependency>
    <!--
      https://mvnrepository.com/artifact/jakarta.validation/jakarta.validation-api -->
    <dependency>
      <groupId>jakarta.annotation</groupId>
      <artifactId>jakarta.annotation-api</artifactId>
    </dependency>
    <!-- <<< end: Annotation -->
    <!-- ************** -->

    <!-- ********************** -->
    <!-- begin: refletions -->
    <!-- https://mvnrepository.com/artifact/org.reflections/reflections -->
    <dependency>
      <groupId>org.reflections</groupId>
      <artifactId>reflections</artifactId>
    </dependency>
    <!-- end: reflections -->
    <!-- ********************** -->

    <!-- ************** -->
    <!-- begin: httpclient -->
    <!-- Source:
    https://mvnrepository.com/artifact/org.apache.httpcomponents.client5/httpclient5 -->
    <dependency>
      <groupId>org.apache.httpcomponents.client5</groupId>
      <artifactId>httpclient5</artifactId>
    </dependency>
    <!-- end: httpclient -->
    <!-- ************** -->

    <!-- ************** -->
    <!-- begin: REST API Documentation -->
    <!-- Source:
    https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-starter-webmvc-ui -->
    <dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
    </dependency>
    <!-- Source:
    https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-starter-webmvc-api -->
    <dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-starter-webmvc-api</artifactId>
    </dependency>
    <!-- Source:
    https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-starter-webflux-ui -->
    <!--    <dependency>-->
    <!--      <groupId>org.springdoc</groupId>-->
    <!--      <artifactId>springdoc-openapi-starter-webflux-ui</artifactId>-->
    <!--    </dependency>-->
    <!-- Source:
    https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-starter-webflux-api -->
    <!--    <dependency>-->
    <!--      <groupId>org.springdoc</groupId>-->
    <!--      <artifactId>springdoc-openapi-starter-webflux-api</artifactId>-->
    <!--    </dependency>-->
    <!-- end: REST API Documentation -->
    <!-- ************** -->

    <!-- ************** -->
    <!-- begin: open.commons -->
    <dependency>
      <groupId>io.github.open-commons</groupId>
      <artifactId>open-commons-core</artifactId>
    </dependency>
    <dependency>
      <groupId>io.github.open-commons</groupId>
      <artifactId>open-commons-ssh</artifactId>
    </dependency>

    <dependency>
      <groupId>com.github.mwiede</groupId>
      <artifactId>jsch</artifactId>
      <version>2.28.0</version>
    </dependency>
    <!-- end: open.commons -->
    <!-- ************** -->

  </dependencies>

  <build>
    <finalName>${build.finalName}</finalName>
    <defaultGoal>install</defaultGoal>
    <sourceDirectory>src/main/java</sourceDirectory>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
        <includes>
          <include>**/*.*</include>
        </includes>
      </resource>
      <resource>
        <directory>${project.basedir}</directory>
        <includes>
          <include>LICENSE</include>
        </includes>
        <targetPath>META-INF</targetPath>
      </resource>
    </resources>
    <plugins>
      <!-- >>> begin: compile -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
      </plugin>
      <!-- <<< end: compile -->
      <!-- >>> begin: source -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-source-plugin</artifactId>
      </plugin>
      <!-- <<< end: source -->
      <!-- >>> begin: javadoc -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
      </plugin>
      <!-- <<< end: javadoc -->
      <!-- Maven Central Deployment plugin -->
      <plugin>
        <groupId>org.sonatype.central</groupId>
        <artifactId>central-publishing-maven-plugin</artifactId>
      </plugin>
      <!-- GPG signature plugin -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-gpg-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
</project>